#!/bin/bash

#  aresbd.bash
#  AresBD
#
#  Copyright (c) 2015 Stsosz Systems. All rights reserved.
#  Don't use this without permission. I'm not responsible
#  for any stupid stuff you do with AresBD.

source ~/aresbd/aresbd.conf
PS3=$menuprompt

# Load Modules
cd "$aresmodules"
for module in *.abdmodule ; do
  if [ -f "$module" ] ; then
    source "$module"
  fi
done

cd ~/aresbd

prompt="abd > "

showSplash

while [ "$command" != "exit" ]
do
  echo -n "$prompt"
  display_attackmode="$attackmode "
  prompt="abd$display_attackmode > "
  read command

if [ "$command" = "set port" ]
then
  setPort
fi

if [ "$command" = "set ip" ]
then
  setIp
fi

if [ "$command" = "set attack mode" ]
then
  setAttack
fi

if [ "$command" = "set script" ]
then
  setScript
fi

if [ "$command" = "set port" ]
then
  setPort
fi

if [ "$command" = "show options" ]
then
  showOpts
fi

# if [ "$command" = "show help" ]
# then
#   showHelp
# fi

if [ "$command" = "start attack" ]
then
  attackLogic
fi

if [ "$command" = "clear" ]
then
  clear
fi

display_attackmode="$attackmode "
prompt="abd$display_attackmode> "

done

echo "Exiting..."
