#!/bin/bash

#  aresbd.bash
#  AresBD
#
#  Copyright (c) 2015 Stsosz Systems. All rights reserved.
#  Don't use this without permission. I'm not responsible
#  for any stupid stuff you do with AresBD.

source ~/aresbd/aresbd.conf
PS3=$menuprompt

# Load Modules
cd "$aresmodules"
for module in *.abdmodule ; do
  if [ -f "$module" ] ; then
    source "$module"
  fi
done

cd ~/aresbd

showSplash

while [ "$command" != "exit" ]
do
  if [[ -z "$attackmode" ]]; then
      prompt="abd > "
      read -rp "$prompt" command
  else
      prompt="abd $attackmode > "
      read -rp "$prompt" command
	fi

  if [ "$command" = "set port" ]
    then
    setPort
  fi

  if [ "$command" = "set ip" ]
    then
    setIp
  fi

  if [ "$command" = "set attack" ]
    then
    setAttack
  fi

  if [ "$command" = "set script" ]
  then
    setScript
  fi

  if [ "$command" = "show options" ]
  then
    showOpts
  fi

  # if [ "$command" = "show help" ]
  # then
  #   showHelp
  # fi

  if [ "$command" = "start attack" ]
  then
    attackLogic
  fi

  if [ "$command" = "clear" ]
  then
    clear
  fi

done

echo "Exiting..."
